''' 
The purpose of this kata is to practice coding for loops with a 
list data set. The use of the range() with the len() to use the 
indices to display the desired result. See the README.md for more
information. 
'''

print("range() with one parameter.")

print("range() with addition.")
for num in range(5):
    t_num = num + 2
    print(t_num)

print("range() with subtraction.")
for num in range(5):
    diff_num = num - 2
    print(diff_num)

print("range() with multiplication.")
for num in range(5):
    multi_num = num * 2
    print(multi_num)

print("range() with division.")
for num in range(5):
    quot_num = num / 2
    print(quot_num)

print("range() with floor division.")
for num in range(5):
    floor_num = num // 2
    print(floor_num)

print("range() with modulo.")
for num in range(5):
    mod_num = num % 2
    print(mod_num)

print("Finding the sum of a range()")
total = 0
for num in range(101):
    total += num
print(total)
# Note: the sum() did not get used, as no data set is being used
# and instead is being generated by range(). Thus, num + num = total

print("The use of a list of words to then imbed as a full quoted\
        string")
words = ["The", "Flash", "is", "a", "superhero."]
string = ""

for word in range(len(words)):
    if word < len(words):
        string += words[word] + " "
    else:
        string += words[word]
print(string)

print("Take the variable string and reverse individual words\
        with each indices.")
rev_string = ""
split_string = string.split()
for s in range(len(split_string)):
    rev_s = split_string[s][::-1]
    if s < len(split_string):
        rev_string += rev_s + " "
    else:
        rev_string += rev_s
print(rev_string)

print("Determine if the variable consisiting of a palidrome is truthy\
        or falsy.")
letters = "civic"
is_palindrome = "is not a palidrome."

for letter in range(len(letters)//2):
    if letters[letter] == letters[len(letters)-letter-1]:
        is_palindrome = "is a plaindrome."
print(f"{letters} is {is_palindrome}.")